name: Deploy to Surge

on:
  push:
    branches:
      - master  # O 'main', según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Esta línea necesita ser actualizada
      
      - name: Install Surge
        run: npm install --global surge
      
      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.surge_token }}
        run: surge . https://mi-proyecto-erick.surge.sh

